package:
  name: time_restricted_eating_experiments
  version: 0.3.0
source:
  sha256: 47e8d67c2c8fd4332863612889be1f541de6498a4c6e5095df78acd870d1c29c
  url: https://files.pythonhosted.org/packages/b6/e8/339dcda07e19e61ddafab536cc435f86f6403a3a43f09a2fef6285ec4504/time_restricted_eating_experiments-0.3.0.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This library provides functions to analyzes food logging data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - time_restricted_eating_experiments
