package:
  name: treets
  version: 1.0.0
source:
  sha256: b547f8c25a72e7ca49922ad3ce2641f9e699c00f4ef69e76fdb697d3f10863b9
  url: https://files.pythonhosted.org/packages/f6/4d/b7f7b77e2b77555f92547523e767b480519b6d4425587fea44e4a0a3012d/treets-1.0.0.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This library provides functions to analyzes food logging data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - treets
