package:
  name: treets
  version: 1.0.2
source:
  sha256: 6020da95999beb09c35533fbb87dd1acc18181bfe8c433250bc6b1b92c52a020
  url: https://files.pythonhosted.org/packages/10/14/c41423993b3b736e003019e33c2ac41454f02f18a8e165c403baeb6bfa91/treets-1.0.2.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This library provides functions to analyzes food logging data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - treets
