package:
  name: public_data_food_analysis_3
  version: 0.2.3
source:
  sha256: 12cc5df5191c9ce3e4d747d57c97e9a7d24ed50fb415cb6892feb453e6b97788
  url: https://files.pythonhosted.org/packages/aa/5f/e8990fd8420ffd1f2a9ecac7b61c27a6eb8d1b032e2970bd62cd0d312c30/public_data_food_analysis_3-0.2.3.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
