package:
  name: public_data_food_analysis_3
  version: 0.1.3
source:
  sha256: 106a8a4e11d1d6bf37d08f35b2a6d212880e6be9977966a953be14ba07614846
  url: https://files.pythonhosted.org/packages/8f/ef/629b56e8523f66da0018372147c7a62ddf06d69fdb1b07e59fae61c1d197/public_data_food_analysis_3-0.1.3.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
