package:
  name: public_data_food_analysis_3
  version: 0.1.5
source:
  sha256: cf16a925f9ba61bfb07a74df69939db3215ab6b98300a1ec1cbceeefb615b57a
  url: https://files.pythonhosted.org/packages/8c/9c/efd549548004561ce7d9dcebec6218ec887ec332c64ef2cd06ad040bf0df/public_data_food_analysis_3-0.1.5.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
