package:
  name: public_data_food_analysis_3
  version: 0.1.8
source:
  sha256: 8dc3305190fbccb5388337870a39a5175866fb940b1699ae6fc17401c5d44f3a
  url: https://files.pythonhosted.org/packages/8d/6c/f3594096fd0f63d5fbed0b9240093a5cf7222df1f780c0622460fb95989d/public_data_food_analysis_3-0.1.8.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
