package:
  name: public_data_food_analysis_3
  version: 0.1.0
source:
  sha256: bb494ac851f61caa07cffbc9f6b82f1937d8c818d90c06236ce05b299e0e7f7a
  url: https://files.pythonhosted.org/packages/ae/b3/6188a3e19dc2a9d9ab8d33463d757e202b92dd1773cb0d8a9ea2c3c2286f/public_data_food_analysis_3-0.1.0.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
