package:
  name: public_data_food_analysis_3
  version: 0.0.4
source:
  sha256: 3d9b02498cc12b8a220f78e7dbed485ff83b3d02d114f2dcb7a2f6dde87fdc86
  url: https://files.pythonhosted.org/packages/ae/cd/f52b04e39c5e6111db187bfc576eda0ad981813fe874822e7867ed65db7c/public_data_food_analysis_3-0.0.4.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
