package:
  name: public_data_food_analysis_3
  version: 0.2.6
source:
  sha256: 4799c1d866d763246ac41f61f10a3d503d375f32c766d8fa7286a7e4186b38bc
  url: https://files.pythonhosted.org/packages/a3/41/423cd2dcc91cfcad366834cb0c718945abe9e0f7e1f9f78495667af66044/public_data_food_analysis_3-0.2.6.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
