package:
  name: public_data_food_analysis_3
  version: 0.0.5
source:
  sha256: 78bd69cee2862caa4c1c53d293fefbd4d16fc63aaeed1dbc30f0c5c07afb976b
  url: https://files.pythonhosted.org/packages/32/02/32188337b355478d04119cc2e1f34edee77ae4e3946641967e52663f78a6/public_data_food_analysis_3-0.0.5.tar.gz
about:
  dev_url: https://QiwenZz.github.io
  doc_url: https://QiwenZz.github.io
  home: https://QiwenZz.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes data from a few input sources.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - QiwenZz
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
  run:
  - pip
  - python
  - packaging
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - datetime
  - nltk
test:
  imports:
  - public_data_food_analysis_3
